import {ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton} from '@clerk/nextjs'
import './globals.css'
import type {Metadata} from 'next'
import {Outfit} from 'next/font/google'
import NavBar from '@/components/NavBar'
import PageTransition from "@/components/PageTransition";
import Footer from "@/components/Home/Footer";
import {Toaster} from 'react-hot-toast';
import './nullstyle.css';

const inter = Outfit({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body className={inter.className}>

            <NavBar/>
            <main>
                <PageTransition>
                    {children}
                </PageTransition>
            </main>
            <Footer/>
            <Toaster position='top-center'/>
            </body>
            </html>
        </ClerkProvider>
    )
}
